title: Xiangxi Shi`s Personal Website
author: Xiangxi Shi
email: 515488476@qq.com
description: > # this means to ignore newlines until "show_exerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
show_excerpts: true # set to true to show excerpts on the homepage

baseurl: # the subpath of your site, e.g. /blog/

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Xiangxi Shi
  tagline: Hey, dude! How's your model goes today? :)
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content


  # generate social links in footer
  social_links:
    #twitter: thelehhman
    github:  citations?user=RpWZqBoAAAAJ&hl=en&oi=ao
    linkedIn: in/thelehhman
    gplus: Sxx1995
    rss: rss
    # dribbble: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # facebook: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com
  navigation:
    homepage: "/"
    CV: "/assets/CV.pdf"
# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: jekyll-theme-modernist

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
